### ISSUE TITLE
Should this also work for video addons?

### ISSUE THREAD

**Issue by puenktchen** [rmrector/script.artwork.helper#2]
... or is it only for the video library database.
I have a video addon that populates 
ListItem.Art(fanart)
ListItem.Art(fanart1)
ListItem.Art(fanart2)
ListItem.Art(fanartX)
I can see those fanart in the thumb selection dialog inside of video details,
but your script doesn't seem to recognize them. Is it not implemented in your script?
If it's missing, is there a chance to implement it? Thanks!

**Comment by rmrector** [comment]
This should work, but I wouldn't be surprised if I missed something for items not in the library. I'll take a look.

**Comment by puenktchen** [comment]
Any news?

**Comment by rmrector** [comment]
This does work OK in my tests.

Try to boil this down to the simplest changes to find out what's going wrong. In Estuary replace the background image with a `multiimage` pointing to Artwork Helper and a short `timeperimage` paired with a stand-alone test plugin that can generate a list of items illustrating this.

**Comment by puenktchen** [comment]
I have the suspicion that the multiimage control doesn't like url's as image paths:
[https://forum.kodi.tv/showthread.php?tid=262975&pid=2857186#pid2857186](url)

**Comment by rmrector** [comment]
That's not true, remote URLs work fine in a multiimage control. Boil it down to the simplest use case.

**Comment by puenktchen** [comment]
Okay, maybe it's because the Emby remote image urls don't have a file extension. I have a hard time to understand this: https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIMultiImage.cpp

**Comment by puenktchen** [comment]
Yeah, the missing file extension is a problem.
Simple test with http://placekitten.com/g/1000/1000 in a multiimage control `<imagepath>plugin://script.artwork.helper/multiimage/?image=http://placekitten.com/g/1000/1000</imagepath>` doesn't show anything in Kodi.

**Comment by puenktchen** [comment]
And because there's nothing you can do about this, your addon is working as expected, i'm closing this.

**Comment by rmrector** [comment]
I can confirm that behavior. However, there _may_ be something I can do in this plugin yet. I'll re-open this while I investigate, but it may still turn out to be a Kodi core thing.

**Comment by rmrector** [comment]
Yup, I can set an image MIME type for the artwork and Kodi will pick it up, so I'll have a fix for this in the next version.

**Comment by puenktchen** [comment]
Great! I'm really excited about it.

**Comment by rmrector** [comment]
This is fixed in the latest version 0.9.1.

Thanks for narrowing this down.

**Comment by puenktchen** [comment]
Working great! Thank you so much.
